name: Integtest

on:
  push:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            coverage: on
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    steps:
      - name: Checkout myself + submodules
        uses: actions/checkout@v3
        with:
          path: src
          fetch-depth: 1
          submodules: true
      - name: Checkout Yunibase
        uses: actions/checkout@v3
        with:
          repository: okuoku/prebuilt-yunibase-proto
          path: yunibase
          fetch-depth: 1
          ref: linux-amd64
          submodules: false
      - name: Install Yunibase
        run: |
          sudo mkdir -p /opt
          sudo ln -s ${{ github.workspace}}/yunibase /opt/yunibase
      - name: Configure
        run: cmake ${{ github.workspace }}/src
      - if: ${{ matrix.coverage }}
        name: "Configure: Enable Coverage"
        run: cmake -DCOVERAGE=ON .
      - name: Build
        run: cmake --build .
      - name: Test (C, Ignore error)
        run: ctest -R C- . || exit 0
      - name: Test (CXX, Ignore error)
        run: ctest -R CXX- . || exit 0
      - if: ${{ matrix.coverage }}
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

