name: Integtest

on:
  push:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    steps:
      - name: Checkout myself + submodules
        uses: actions/checkout@v3
        with:
          path: src
          fetch-depth: 0
          submodules: true
      - name: Download Yunibase
        run: curl -L --output yunibase.tar.gz https://api.github.com/repos/okuoku/prebuilt-yunibase-proto/tarball/linux-amd64
      - name: Extract Yunibase
        run: |
          tar zxf yunibase.tar.gz
          mv mv okuoku-prebuilt-yunibase-proto-* yunibase
      - name: Install Yunibase
        run: |
          sudo mkdir -p /opt
          sudo ln -s yunibase /opt/yunibase
      - name: Configure
        run: cmake -G Ninja ${{ github.workspace }}/src
      - name: Build
        run: ninja
      - name: Test (Ignore error)
        run: ctest --verbose . || exit 0

