name: Integtest

on:
  push:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    steps:
      - name: Checkout myself + submodules
        uses: actions/checkout@v3
        with:
          path: src
          fetch-depth: 1
          submodules: true
      - name: Checkout Yunibase
        uses: actions/checkout@v3
        with:
          path: yunibase
          fetch-depth: 1
          ref: linux-amd64
          submodules: false
      - name: Install Yunibase
        run: |
          sudo mkdir -p /opt
          sudo ln -s ${{ github.workspace}}/yunibase /opt/yunibase
      - name: Configure
        run: cmake -G Ninja ${{ github.workspace }}/src
      - name: Build
        run: ninja
      - name: Test (Ignore error)
        run: ctest --verbose . || exit 0

