name: CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix: 
        include:
          #- os: windows-2022
          #  host: native
          #  builder: msbuild
          - os: windows-2022
            host: cygwin-ltsc2022
            builder: ninja
          - os: macos-latest
            host: native
            builder: make
          - os: ubuntu-latest
            host: native
            builder: make
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Prepare"
        run: |
          cmake -DBUILDER=${{ matrix.builder }} -DHOST=${{ matrix.host }} -DPHASE=prepare -P integ/integbuild.cmake

      - name: "Build"
        run: |
          cmake -DBUILDER=${{ matrix.builder }} -DHOST=${{ matrix.host }} -DPHASE=build -P integ/integbuild.cmake

      - name: "Test"
        run: |
          cmake -DBUILDER=${{ matrix.builder }} -DHOST=${{ matrix.host }} -DPHASE=test -P integ/integbuild.cmake

